# Generated by Django 4.1.2 on 2022-10-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="headshot",
            field=models.ImageField(
                blank=True, null=True, upload_to="author_headshots"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
